### ISSUE TITLE
Build a Microservice in NodeJS with one route for it be able of update user in the information system.

### ISSUE THREAD

**Issue by admezalo** [admezalo/town_hall-viota#4]

**Comment by DanteAndres** [comment]
Microservice has been built, for this moment, this will be found in the next route:

https://user-system-api.herokuapp.com/api/updatePassForAdmin/:id

![image](https://user-images.githubusercontent.com/49260309/93007902-e1e15680-f533-11ea-894a-ae5a08001ea2.png)
