### ISSUE TITLE
Deployent Microservice with all routes and functionalities for demo.

### ISSUE THREAD

**Issue by admezalo** [admezalo/town_hall-viota#7]

**Comment by DanteAndres** [comment]
Microservice has been built, for this moment, the next routes belog the route https://user-system-api.herokuapp.com:

- [ ] Get One User -> https://user-system-api.herokuapp.com/api/getOneUserSystem/:id 

- [ ] Get All Users -> https://user-system-api.herokuapp.com/api/getAllUserSystem (Needs a token)

- [ ] Create One User -> https://user-system-api.herokuapp.comapi/createUserSystem (Needs a Body and a token)

- [ ] Login -> https://user-system-api.herokuapp.com/api/loginUserSystem (Needs a Body and a token)

- [ ]Update Password -> https://user-system-api.herokuapp.com/api/updatePassUserSystem (Needs a Body and a token)

- [ ] Allow Update Password -> http://localhost:3000/api/updatePassForAdmin/:id

- [ ] Delete One User -> http://localhost:3000/api/deleteUserSystem/:id
